### PR TITLE
Unified `chain_break_method`'s API.

### PR DESCRIPTION
**Pull request by frechette-alex**

### CODE REVIEW

**Comment by bellert** [comment]
Should the other chain break methods (that don't require additional arguments) also be converted to classes to make the interface parallel, or is this overkill?

**Comment by frechette-alex** [comment]
I think it may be overkill.

The interface is only to have a `__call__` method that accepts certain arguments. A simple function satisfies that interface (if it quacks like a duck ...). The need for an object is when the actually `chain_break_method` requires state/additional arguments.

**Comment by bellert** [comment]
This is true, but it isn't immediately obvious (at least to me) when first glancing at the code, which things are chain break methods. Maybe instead of sub-classing `object`, should it subclass some kind of `TemplateChainBreakMethod`? Again, the minimal requirement is that it has a `__call__` method that accepts `sample` and `embedding`, but it looks more uniform to me. (I realize this is even more overkill.)

**Comment by frechette-alex** [comment]
Technically, before this pull request there was an implicitly declared "interface" for `chain_break_method` that you needed to satisfy if you wanted to provide your own. It didn't require a template of some sort. I am just making this implicit "interface" uniform.

I'd be wary of using interfaces in a language (python) that typically does not need any, especially for objects as simple as this. I think the documentation and the simplicity of code should be enough to communicate `chain_break_method`'s contract. But that's my opinion :).

**Comment by bellert** [comment]
For sure. It definitely still conforms to that. I'll leave it at that and let @arcondello chime in.

**Comment by arcondello** [comment]
Ok, I think I am convinced. Thanks everyone!

**Pull request merged**
